# Dependencies
markdown:         kramdown
highlighter:      rouge
excerpt_separator: <!--more-->

# Setup
title:            Akash Nair
tagline:          'DevOps Engineer | Berlin'
description:	  'I am a DevOps Engineer and an automation extremist. I design, build and implement architectures on the cloud'
url:              https://akashnair.com
baseurl:          ''
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'Akash Nair'
  url:            https://akashnair.com

paginate:         5
paginate_path:    '/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

# Custom vars
#version:            3.7.0
#sidebar_home_link:  true
#sidebar_blog_link:  '/'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.
disqus:
  shortname:	    Mektoplack99
github:
  repo:             https://github.com/slashr
